name = "dnd-mietling-ws"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{ name = "GAME_SESSION", class_name = "GameSession" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameSession"]
